export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SHOW_IN_DETAILS_VIEW = 'SHOW_IN_DETAILS_VIEW';
export const SHOW_CART = 'SHOW_CART';
export const CLEAR_CART = 'CLEAR_CART';

export const START_GET_PRODUCTS = 'START_GET_PRODUCTS';
export const SUCCESS_GET_PRODUCTS = 'SUCCESS_GET_PRODUCTS';
export const ERROR_GET_PRODUCTS = 'ERROR_GET_PRODUCTS';
